    
---

- hosts: all

#  sudo: yes

  tasks:

 #   - name: Installing OpenOffice 

 # #    command: "{{ item }}"

  #    with_items :

    #   - apt-get install -y wget
     #  - wget https://sourceforge.net/projects/openofficeorg.mirror/files/4.1.6/binaries/en-US/Apache_OpenOffice_4.1.6_Linux_x86-64_install-deb_en-US.tar.gz
      # - tar xvf Apache_OpenOffice_4.1.6_Linux_x86-64_install-deb_en-US.tar.gz
      # - cd en-US/DEBS
      # - sudo dpkg -i  *.deb
      # - cd desktop-integration
      # - sudo dpkg -i *deb
       
       - name: Downloading Apache Open Office
    get_url:
    url: https://sourceforge.net/projects/openofficeorg.mirror/files/4.1.6/binaries/en-US/Apache_OpenOffice_4.1.6_Linux_x86-64_install-deb_en-US.tar.gz
    dest: /home/test/Desktop/Apache_OpenOffice_4.1.6_Linux_x86-64_install-deb_en-US.tar.gz
    
   tasks:
   - name : Extracting Open Office
      
    unarchive:
    src: /home/test/Desktop/Apache_OpenOffice_4.1.6_Linux_x86-64_install-deb_en-US.tar.gz
    dest: /home/test/Desktop/Apache_OpenOffice_4.1.6_Linux_x86-64_install-deb_en-US
    
   tasks:
   - name : Installing the .deb File 
     command : cd /home/test/Desktop/Apache_OpenOffice_4.1.6_Linux_x86-64_install-deb_en-US/en-US/DEBS
     command : sudo dpkg -i *.deb
     command : cd desktop-integration
     command : sudo dpkg -i *deb
       
  
       
       
       
